version: '2.4'
services:
  web: 
    container_name: pos-ui-demo
    image: 'edgify/edgify-pos-ui-demo:shufersal3'
    environment:
      - REACT_APP_PREDICTOR_HOST=localhost
    #volumes:
    #  - /home/ubuntu/config.json:/usr/share/nginx/html/clients/config.json      
    ports:
      - '3000:80'
